### ISSUE TITLE
컴포넌트 경로 인식 오류

### ISSUE THREAD

**Issue by skojphy** [kheeyaa/lucky-ducky#27]
<img width="575" alt="image" src="https://user-images.githubusercontent.com/42148741/215428963-0cdf714d-b56d-45a3-8de6-b3c80b9137b4.png">
GameName과 A11y 컴포넌트 경로가 인식이 되지 않는데 왜 그럴까요?ㅠㅠ

**Comment by piggmme** [comment]
오잉?! 왜그러죠 확인해볼게요

**Comment by piggmme** [comment]
저는 오류 발생 안하는데 혹시 vsc 껏다가 다시 켜보실래용?

**Comment by skojphy** [comment]
> 저는 오류 발생 안하는데 혹시 vsc 껏다가 다시 켜보실래용?

대박ㅋㅋㅋㅋㅋ해결됐어요 진리의 껐켰...
